# Generated by Django 6.0.3 on 2026-03-10 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_doctors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departments',
            new_name='Department',
        ),
        migrations.RenameModel(
            old_name='Doctors',
            new_name='Doctor',
        ),
    ]
